# Generated by Django 3.2.9 on 2021-11-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_tejido_tessiu'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField()),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.RenameField(
            model_name='tessiu',
            old_name='temperatura',
            new_name='color',
        ),
        migrations.AddField(
            model_name='tessiu',
            name='inflammation',
            field=models.FloatField(default=0, verbose_name='inlamacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tessiu',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='temperatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tessiu',
            name='name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.paciente'),
            preserve_default=False,
        ),
    ]
