# Generated by Django 3.2.9 on 2021-11-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20211117_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tessiu',
            name='inflammation',
            field=models.FloatField(verbose_name='inflamacion'),
        ),
    ]
