# Generated by Django 3.2.9 on 2021-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20211117_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
