# Generated by Django 3.2.9 on 2021-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_tessiu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='distancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(verbose_name='distancias')),
                ('union', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'distancia',
                'verbose_name_plural': 'distancias',
            },
        ),
    ]
