# Generated by Django 3.2.9 on 2021-11-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_distancia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancia',
            name='union',
        ),
        migrations.AddField(
            model_name='distancia',
            name='r1',
            field=models.IntegerField(default=0, verbose_name='r1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distancia',
            name='r2',
            field=models.IntegerField(default=0, verbose_name='r2'),
            preserve_default=False,
        ),
    ]
